### ISSUE TITLE
integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. 

### ISSUE THREAD

**Issue by luisleonardo** [netsoft-ruidias/ha-custom-component-precoscombustiveis#5]
Só para informar que tenho o seguinte erro nos logs. Obrigado.

Home Assistant 2023.3.6
Supervisor 2023.03.3
Operating System 10.0.rc2
Frontend 20230309.1 - latest

*****************

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 00:51:00 (1 occurrences)
Last logged: 00:51:00

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for precoscombustiveis using this method at custom_components/precoscombustiveis/__init__.py, line 37: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by PedroQ** [comment]
This pull request fixes the issue:; https://github.com/netsoft-ruidias/ha-custom-component-precoscombustiveis/pull/6

**Comment by netsoft-ruidias** [comment]
Resolved in version v1.3.0
