### ISSUE TITLE
Error setting up entry in version 2023.5.2

### ISSUE THREAD

**Issue by vcoelho24** [netsoft-ruidias/ha-custom-component-precoscombustiveis#7]
Aparece-me este erro ao adicionar a integração:

Info do sistema:
Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

Log do erro:
Logger: homeassistant.config_entries
Source: custom_components/precoscombustiveis/__init__.py:37
Integration: DGEG.PT Precos Combustiveis ([documentation](https://github.com/netsoft-ruidias/ha-custom-component-precoscombustiveis/blob/main/README.md), [issues](https://github.com/netsoft-ruidias/ha-custom-component-precoscombustiveis/issues))
First occurred: May 6, 2023 at 20:19:18 (1 occurrences)
Last logged: May 6, 2023 at 20:19:18

Error setting up entry 67265: AUCHAN AVEIRO for precoscombustiveis
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/precoscombustiveis/__init__.py", line 37, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by mdiazgoncalves** [comment]
Vê o issue #5

**Comment by vcoelho24** [comment]
Resolvido, muito obrigado @mdiazgoncalves
