### ISSUE TITLE
sensor state_class total gives incorrect statistics

### ISSUE THREAD

**Issue by PBudmark** [netsoft-ruidias/ha-custom-component-precoscombustiveis#8]
Hello,
v1.3.0. Using state_class total (SensorStateClass.TOTAL) makes the statistics incorrect, creating summation of values.
state_class measurement (SensorStateClass.MEASUREMENT) seems more correct for fuel prices, statistics will create mean, min and max
best regards Per-Ake

**Comment by netsoft-ruidias** [comment]
Fix with PR https://github.com/netsoft-ruidias/ha-custom-component-precoscombustiveis/pull/9
